"""add player ids to games

Revision ID: 29010bc51ffb
Revises: 7213a7799f9e
Create Date: 2026-09-23 19:39:35.716745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29010bc51ffb'
down_revision: Union[str, Sequence[str], None] = '7213a7799f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('white_player_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('black_player_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'players', ['black_player_id'], ['player_id'])
    op.create_foreign_key(None, 'games', 'players', ['white_player_id'], ['player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'games', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'black_player_id')
    op.drop_column('games', 'white_player_id')
    # ### end Alembic commands ###
