"""add move analysis

Revision ID: 2d78fc425b2a
Revises: f721818a5ab8
Create Date: 2026-09-23 15:58:50.613374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d78fc425b2a'
down_revision: Union[str, Sequence[str], None] = 'f721818a5ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move_analysis',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=10), nullable=False),
    sa.Column('evaluation_loss', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('analysis_id'),
    sa.UniqueConstraint('position_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move_analysis')
    # ### end Alembic commands ###
