"""add move information to positions

Revision ID: 54137c311507
Revises: d96ecf7becf8
Create Date: 2026-09-23 02:28:25.533465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54137c311507'
down_revision: Union[str, Sequence[str], None] = 'd96ecf7becf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('ply', sa.Integer(), nullable=False))
    op.add_column('positions', sa.Column('move_uci', sa.String(length=10), nullable=False))
    op.add_column('positions', sa.Column('move_san', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'move_san')
    op.drop_column('positions', 'move_uci')
    op.drop_column('positions', 'ply')
    # ### end Alembic commands ###
