"""add positional analysis

Revision ID: ba09ab2b3f6f
Revises: 29010bc51ffb
Create Date: 2026-09-28 22:34:28.965413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba09ab2b3f6f'
down_revision: Union[str, Sequence[str], None] = '29010bc51ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'move_analysis',
        sa.Column(
            'positional_analysis',
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'{}'::json"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('move_analysis', 'positional_analysis')
    # ### end Alembic commands ###
