"""add tactical analysis to move analysis

Revision ID: d220f2aca1bb
Revises: 2d78fc425b2a
Create Date: 2026-09-23 18:16:04.286254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd220f2aca1bb'
down_revision: Union[str, Sequence[str], None] = '2d78fc425b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'move_analysis',
    sa.Column(
        'tactical_analysis',
        sa.JSON(),
        nullable=False,
        server_default=sa.text("'{}'::json")
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('move_analysis', 'tactical_analysis')
    # ### end Alembic commands ###
