"""add pgn hash to games

Revision ID: f721818a5ab8
Revises: 54137c311507
Create Date: 2026-09-23 14:40:38.266680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f721818a5ab8'
down_revision: Union[str, Sequence[str], None] = '54137c311507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('pgn_hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'games', ['pgn_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_column('games', 'pgn_hash')
    # ### end Alembic commands ###
