from datetime import datetime
import chess
import hashlib
from chess_coach.database.models import Game, Position, EngineAnalysis, MoveAnalysis
from sqlalchemy import select



def load_game(session, game):
    """
    Store one python-chess Game and all positions generated by its moves.
    """

    # 1. Convert the game to PGN text
    pgn_text = str(game)

    # 2. Create a deterministic fingerprint
    pgn_hash = hashlib.sha256(
        pgn_text.encode("utf-8")
    ).hexdigest()

    # 3. Check whether this game already exists
    existing_game = (
        session.query(Game)
        .filter_by(pgn_hash=pgn_hash)
        .first()
    )

    if existing_game:
        print(f"Game already exists: {pgn_hash}")
        return existing_game

    # 4. Extract PGN headers
    headers = game.headers

    game_date = None

    if headers.get("Date"):
        try:
            from datetime import datetime

            game_date = datetime.strptime(
                headers["Date"],
                "%Y.%m.%d"
            ).date()
        except ValueError:
            pass

    # 5. Create the Game record
    db_game = Game(
        white_player=headers.get("White", "Unknown"),
        black_player=headers.get("Black", "Unknown"),
        result=headers.get("Result", "*"),
        date=game_date,
        event=headers.get("Event"),
        pgn=pgn_text,
        pgn_hash=pgn_hash,
    )

    session.add(db_game)
    session.flush()

    # 6. Generate and store positions
    board = game.board()

    for ply, move in enumerate(game.mainline_moves(), start=1):

        # SAN must be calculated BEFORE push()
        move_san = board.san(move)
        move_uci = move.uci()

        board.push(move)

        position = Position(
            game_id=db_game.game_id,
            ply=ply,
            move_number=(ply + 1) // 2,
            move_uci=move_uci,
            move_san=move_san,
            fen=board.fen(),
        )

        session.add(position)

    return db_game


def get_game_fingerprint(game):
    pgn_text = str(game)
    return hashlib.sha256(pgn_text.encode("utf-8")).hexdigest()






def get_unanalyzed_positions(session):
    """
    Return positions that do not yet have Stockfish analysis.
    """

    statement = (
        select(Position)
        .outerjoin(
            EngineAnalysis,
            Position.position_id == EngineAnalysis.position_id
        )
        .where(
            EngineAnalysis.position_id.is_(None)
        )
    )

    return session.scalars(statement).all()


def get_positions_with_analysis(session):
    statement = (
        select(Position, EngineAnalysis)
        .join(
            EngineAnalysis,
            Position.position_id == EngineAnalysis.position_id
        )
        .order_by(Position.game_id, Position.ply)
    )

    return session.execute(statement).all()

def save_move_analysis(session, analysis):
    existing = (
        session.query(MoveAnalysis)
        .filter_by(position_id=analysis["position_id"])
        .first()
    )

    if existing:
        # Only fill tactical analysis if it hasn't been populated yet
        if not existing.tactical_analysis:
            existing.tactical_analysis = analysis["tactical_analysis"]

        return existing

    move_analysis = MoveAnalysis(
        position_id=analysis["position_id"],
        player=analysis["player"],
        evaluation_loss=analysis["evaluation_loss"],
        classification=analysis["classification"],
        tactical_analysis=analysis["tactical_analysis"],
    )

    session.add(move_analysis)
    return move_analysis